schema = 3

[mod]
  [mod."github.com/go-logfmt/logfmt"]
    version = "v0.6.0"
    hash = "sha256-RtIG2qARd5sT10WQ7F3LR8YJhS8exs+KiuUiVf75bWg="
  [mod."github.com/godror/godror"]
    version = "v0.42.1"
    hash = "sha256-axO5J5BruPyekGhRlk2FR1dpdVFS0dMci3ZspsqU68w="
  [mod."github.com/godror/knownpb"]
    version = "v0.1.1"
    hash = "sha256-tblRsuYD9AD/vDH+3ZkuR5Ua6t9cNfdOQ0a/Zl5v+OE="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20240318143956-a85f2c67cd81"
    hash = "sha256-HjEmpjgXqIuGc5rsTVkg6OPAN2fGhfkska7cwRu1qaw="
  [mod."google.golang.org/protobuf"]
    version = "v1.33.0"
    hash = "sha256-cWwQjtUwSIEkAlAadrlxK1PYZXTRrV4NKzt7xDpJgIU="
